apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "pingdatagovernance.name" . }}
    helm.sh/chart: {{ include "pingdatagovernance.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "pingdatagovernance.fullname" . }}-env-vars
data:
  PING_IDENTITY_ACCEPT_EULA: {{ .Values.license.acceptEULA | quote  }}
  PD_LOG_LEVEL: {{ .Values.pingdatagovernance.logging | quote }}
{{ toYaml .Values.pingdatagovernance.envs | indent 2 }}
